### ISSUE TITLE
Move contents of `main` section in config file to the top-level?

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/numbat#243]
i.e. change this:
```toml
[main]
prompt = "numbat> "

[exchange-rates]
# ...
```

to this:

```toml
prompt = "numbat> "

[exchange-rates]
# ...
```

All software which I have installed and have TOML config files for (Helix and Chezmoi, admittedly n=2 is not a satisfactory sample size) also have top-level fields for the "main" config fields. Is there a reason to keep it as-is?
