### ISSUE TITLE
Errors in config file don't point to correct span

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/numbat#295]
To reproduce, write this to your config file:
    
```toml
intro-banner = "short"
promtp = "numbat> "
#   ^^ see the typo here
```
then run `numbat`, which will error with this output:
```
Error while loading /home/triallax/.config/numbat/config.toml: TOML parse error at line 1, column 1
  |
1 | intro-banner = "short"
  | ^^^^^^^^^^^^^^^^^^^^^^
unknown field `promtp`
```
